//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GumiServisModelEntities : DbContext
    {
        public GumiServisModelEntities()
            : base("name=GumiServisModelEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Bok> Boks { get; set; }
        public virtual DbSet<Klijent> Klijents { get; set; }
        public virtual DbSet<Mjesto> Mjestoes { get; set; }
        public virtual DbSet<Poslovnica> Poslovnicas { get; set; }
        public virtual DbSet<Radni_nalog> Radni_nalog { get; set; }
        public virtual DbSet<Raspored> Rasporeds { get; set; }
        public virtual DbSet<Skladiste> Skladistes { get; set; }
        public virtual DbSet<Ugovor> Ugovors { get; set; }
        public virtual DbSet<UslugaProdaja> UslugaProdajas { get; set; }
        public virtual DbSet<Vozilo> Voziloes { get; set; }
        public virtual DbSet<Zaposlenik> Zaposleniks { get; set; }
    }
}
