//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class UslugaProdaja
    {
        public int Id { get; set; }
        public string Naziv_us_pro { get; set; }
        public double Jed_cijena { get; set; }

        public override string ToString()
        {
            return Naziv_us_pro;
        }
    }
}
